SELECT
    COMPOUND_STRUCTURES.canonical_smiles,
    MOLECULE_DICTIONARY.chembl_id,
    ACTIVITIES.STANDARD_TYPE,
    ACTIVITIES.STANDARD_RELATION,
    ACTIVITIES.STANDARD_VALUE,
    ACTIVITIES.STANDARD_UNITS
FROM MOLECULE_DICTIONARY
JOIN COMPOUND_STRUCTURES ON MOLECULE_DICTIONARY.molregno = COMPOUND_STRUCTURES.molregno
JOIN ACTIVITIES ON MOLECULE_DICTIONARY.molregno = ACTIVITIES.molregno
JOIN ASSAYS ON ACTIVITIES.ASSAY_ID = ASSAYS.ASSAY_ID
WHERE ASSAYS.chembl_id = 'CHEMBL4649971'
  AND ACTIVITIES.standard_value IS NOT NULL
  AND ACTIVITIES.standard_relation IS NOT NULL
  AND ACTIVITIES.standard_relation = '='
