COPY (
  SELECT DISTINCT TID, PREF_NAME FROM ACTIVITIES
  JOIN ASSAYS USING (ASSAY_ID)
  JOIN TARGET_DICTIONARY USING (TID)
  WHERE STANDARD_TYPE = 'Ki'
  AND STANDARD_VALUE IS NOT NULL
  AND STANDARD_RELATION = '='
)
TO '/path/td.csv'
( FORMAT CSV )
